### ISSUE TITLE
"clone" (and tool-tips)

### ISSUE THREAD

**Issue by shiffman** [catarak/p5.js-web-editor#24]
I'm opening this issue to discuss the term for saving a copy of a project.  This is relevant for when you open a project with a URL from someone else's account (like your teacher) and then want to save it to your own account.

Some options are:
* clone
* save as
* save to username
* fork

Whatever we use I noticed the default "tool-tip" on the editor menu all say: "project-menu" and we could use the tool tip to explain the behavior further.

**Comment by shiffman** [comment]
In discussion at the user testing group today we came up with the following changes:

* "export" should change to "download"
* "clone" can be removed and "save" saves to your account if it's not already your project. If it is your project there should be a "save as" option.

**Comment by catarak** [comment]
fixed in eb85e49
