### ISSUE TITLE
Totally Unsolicited Font Opinions™  

### ISSUE THREAD

**Issue by bensk** [catarak/p5.js-web-editor#26]
Proxima Nova & [Operator](http://www.typography.com/blog/introducing-operator):
![image](https://cloud.githubusercontent.com/assets/7450756/17035864/b5254934-4f57-11e6-865f-1ae232de6dc2.png)

**Comment by catarak** [comment]
cc @lmccart

The non-Editor font will be changed from Montserrat to Avenir, which will be a lot better, but Operator is super cool.

**Comment by lmccart** [comment]
operator is cool! however, I think this should maintain the graphic design of the website and desktop editor, meaning Inconsolatas for the code text, Avenir and Times for the rest of the text. maybe operator is something to consider if we do a graphic design refresh sometime in the future.
