### ISSUE TITLE
iframe has maximum height of ~200px?

### ISSUE THREAD

**Issue by shiffman** [catarak/p5.js-web-editor#28]
I'm only seeing about 200px along the vertical axis in the iframe where the sketch is rendered:

![p5-editor](https://cloud.githubusercontent.com/assets/191758/17088166/c4b03932-51e5-11e6-9815-1a065e8f3ac3.gif)

btw, this is chrome Version 51.0.2704.103 (64-bit) mac OS X.

**Comment by catarak** [comment]
i was fixing some styling issues for IE and Edge, which probably caused this. Will look into this later today.

**Comment by catarak** [comment]
fixed on master and deployed!
