### ISSUE TITLE
Safari editor-console styling

### ISSUE THREAD

**Issue by MathuraMG** [catarak/p5.js-web-editor#31]
While opening the [IDE](http://52.41.35.139:8000/) in safari (Version 9.1.2 (10601.7.7)) - the editor-console area shows up as below - 

---

![screen shot 2016-08-05 at 2 56 07 pm](https://cloud.githubusercontent.com/assets/5505598/17451729/220feaaa-5b37-11e6-8ddc-1bc5c9b65dfa.png)

---

On adding lines to the editor, the console area moves down too but it's not there on coming back up to the top of the IDE.

---

![screen shot 2016-08-05 at 2 56 23 pm](https://cloud.githubusercontent.com/assets/5505598/17451733/274e1b9a-5b37-11e6-8b1a-4298b0497957.png)

---

![screen shot 2016-08-05 at 2 56 29 pm](https://cloud.githubusercontent.com/assets/5505598/17451741/2fe5b7ae-5b37-11e6-8c9c-1ff9a403b69c.png)

---

**Comment by catarak** [comment]
Is this on master? I've been working on a fix for this on a local branch, to be merged into development soon.

**Comment by MathuraMG** [comment]
I tested on this link -[ 52.41.35.139:8000](52.41.35.139:8000), so I believe that is master?

**Comment by catarak** [comment]
This is mostly fixed on master--for some reason, on Safari, I can't make the height of the code editor responsive, but it works on Firefox and Chrome.
