### ISSUE TITLE
Preferences modal shows up behind canvas if sketch is running

### ISSUE THREAD

**Issue by indefinit** [catarak/p5.js-web-editor#45]
Looks like a styling bug where the preferences modal is showing up behind the canvas on the right side.  Tested in Chrome 53.

Steps to repro:
1. press play button
2. press gear icon

**Comment by catarak** [comment]
Hah I know exactly why this is happening 😄 I'm on it!

**Comment by catarak** [comment]
For some reason I can't reproduce this, just updated the CSS I thought was the issue so let me know if it's fixed.

**Comment by shiffman** [comment]
It's working for me FYI.
